model:
  base_learning_rate: 4.5e-06
  target: VQGAN.model.vqgan.VQModel
  params:
    n_embed: 16384
    embed_dim: 256
    image_key: image
    ddconfig: 
      double_z: False
      z_channels: 256
      resolution: 512
      in_channels: 3
      out_ch: 3 
      ch: 64
      ch_mult: [1,2,4,8,8,8]
      num_res_blocks: 1
      attn_resolutions: [64]
      dropout: 0.0

    lossconfig:
      target: VQGAN.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 30
        disc_weight: 0.01
        codebook_weight: 1.0

data:
  target: util.DataModuleFromConfig
  params:
    batch_size: 6
    num_workers: 4
    train:
      target: data.smokeRing2.SmokeRingTrain
      params:
        root: path/to/dataset
        toTensor: True
        normalizeImage: True
    
    # validation:
    #   target: data.smokeRing.SmokeRingVal
    #   params:
    #     root: path/to/dataset
    #     toTensor: True
    #     normalizeImage: True


lightning:
  trainer:
    max_epochs: 100
    devices: 1
    accelerator: gpu


