model:
  base_learning_rate: 4.5e-06
  target: VQGAN.model.vqgan.VQModel
  params:
    n_embed: 2048
    embed_dim: 256
    image_key: image
    ddconfig: 
      double_z: False
      z_channels: 256
      resolution: 512
      in_channels: 3
      out_ch: 3 
      ch: 64
      ch_mult: [1,2,4,8]
      num_res_blocks: 1
      attn_resolutions: [128]
      dropout: 0.0

    lossconfig:
      target: VQGAN.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 50
        disc_weight: 0.8
        codebook_weight: 1.0

data:
  target: util.DataModuleFromConfig
  params:
    batch_size: 4
    num_workers: 4
    train:
      target: data.smokeRing.SmokeRingTrain
      params:
        root: /data/data2/tomoya/data/SmokeLing/VolumeRendering/data2
        toTensor: True
        normalizeImage: True
        normalizeParams: False
    
    # validation:
    #   target: data.smokeRing.SmokeRingVal
    #   params:
    #     root: /data/data2/tomoya/data/SmokeLing/VolumeRendering/data2
    #     toTensor: True
    #     normalizeImage: True
    #     normalizeParams: False


lightning:
  trainer:
    max_epochs: 200
    devices: 1
    accelerator: gpu


